[build]
    command = "npm run build"
    publish = "_site/"
    environment = { MERMAID_MIXUP_ENVIRONMENT = "development" }

[context.deploy-preview]
    MERMAID_MIXUP_ENVIRONMENT = "production-preview"

[context.branch-deploy]
    MERMAID_MIXUP_ENVIRONMENT = "production-preview"

[context.production.environment]
    MERMAID_MIXUP_ENVIRONMENT = "production"