[build]
    command = "npm run build"
    publish = "_site/"
    environment = { MERMAID_MIXUP_ENVIRONMENT = "development" }

[context.production]
    environment = { MERMAID_MIXUP_ENVIRONMENT = "production" }