[build]
    command = "npm run build"
    publish = "_site/"

[context.deploy-preview.environment]
    MERMAID_MIXUP_ENVIRONMENT = "production-preview"
    # Disable Etsy API communication in non-production environments
    ETSY_API_KEY = ""

[context.branch-deploy.environment]
    MERMAID_MIXUP_ENVIRONMENT = "production-preview"
    # Disable Etsy API communication in non-production environments
    ETSY_API_KEY = ""

[context.production.environment]
    MERMAID_MIXUP_ENVIRONMENT = "production"